// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqAxBPtH-f6OHCqUGzSx8xeePreq7gBM4',
    appId: '1:313997128720:web:7ee7baadcec7528aa88695',
    messagingSenderId: '313997128720',
    projectId: 'todo-list-9e2c5',
    authDomain: 'todo-list-9e2c5.firebaseapp.com',
    storageBucket: 'todo-list-9e2c5.appspot.com',
    measurementId: 'G-3LV43247XV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZOuP2JfjcLu2RVved3y5igiImJI5oudg',
    appId: '1:313997128720:android:df549a99305f58cca88695',
    messagingSenderId: '313997128720',
    projectId: 'todo-list-9e2c5',
    storageBucket: 'todo-list-9e2c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMSbx5oBdviYeRci95_cC-jz1Y59zCtjM',
    appId: '1:313997128720:ios:8e213a722e3445d4a88695',
    messagingSenderId: '313997128720',
    projectId: 'todo-list-9e2c5',
    storageBucket: 'todo-list-9e2c5.appspot.com',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMSbx5oBdviYeRci95_cC-jz1Y59zCtjM',
    appId: '1:313997128720:ios:c43b888c3b8ba012a88695',
    messagingSenderId: '313997128720',
    projectId: 'todo-list-9e2c5',
    storageBucket: 'todo-list-9e2c5.appspot.com',
    iosBundleId: 'com.example.todoList.RunnerTests',
  );
}
